Repository ManojGowda2006/Kalviance, pull requests merged in 2025-08, with the labels that each got.

#1 login page
  client/.gitignore
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/imgkalviance.png
  client/public/logokalvian.png
  client/public/vite.svg
  client/src/App.css
  client/src/App.jsx
  client/src/assets/react.svg
  client/src/icons/LogoIcon.jsx
  client/src/index.css
  client/src/main.jsx
  client/src/pages/Login.jsx
  client/vite.config.js
Labels: Possible security concern, Review effort 2/5

#3 Login-Schema
  server/database/database.js
  server/models/user.js
  server/server.js
Labels: Review effort 2/5

#4 announcement_achievement_pages_created
  client/package-lock.json
  client/package.json
  client/public/image.png
  client/public/imgkalviance.png
  client/public/mobkalp.png
  client/src/App.jsx
  client/src/pages/Achievement.jsx
  client/src/pages/Announcement.jsx
  client/src/pages/Login.jsx
Labels: Review effort 3/5

#5 added achievement schema and announcement schema
  server/models/achievement.js
  server/models/announcement.js
Labels: Review effort 2/5

#7 Readme
  README.md
Labels: Review effort 1/5

#8 achievement_page
  client/src/pages/Achievement.jsx
  server/package-lock.json
  server/package.json
Labels: Review effort 3/5

#10 changed the ui of announcements n achievements page
  client/src/assets/logo.png
  client/src/pages/Achievement.jsx
  client/src/pages/Announcement.jsx
Labels: Review effort 2/5

#9 achievement_page
  client/src/pages/Achievement.jsx
Labels: Review effort 2/5
